# Identify & Track Marine Heatwaves using `spot_the_blOb`

## Processing Steps:
1. Fill holes in the binary data, using `dask_image.ndmorph` -- up to `R_fill` cells in radius.
2. Filter out small objects -- area less than the `area_filter_quartile` of the distribution of objects.
3. Identify objects in the binary data, using `dask_image.ndmeasure`.
4. Manually connect objects across time, applying Sun et al. 2023 criteria:
    - Connected Blobs must overlap by at least `overlap_threshold=50%` of the smaller blob.
    - Merged Blobs retain their original ID, but split the blob based on parent centroid locality.
5. Cluster and reduce the final object ID graph using `scipy.sparse.csgraph.connected_components`.

N.B.: Exploits parallelised `Dask` operations with optimised chunking using `flox` for memory efficiency and speed \
N.N.B.: This example using 40 years of Daily outputs at 0.25° resolution takes ~6 minutes on 128 total cores.

In [1]:
import xarray as xr
import dask
from getpass import getuser
from pathlib import Path

import spot_the_blOb as blob
import spot_the_blOb.helper as hpc

In [2]:
# Start Dask Cluster
client = hpc.StartLocalCluster(n_workers=32, n_threads=2)

Memory per Worker: 7.86 GB
Hostname is  l20134
Forward Port = l20134:8787
Dashboard Link: localhost:8787/status


In [3]:
# Load Pre-processed Data (cf. `01_preprocess_extremes.ipynb`)

file_name = Path('/scratch') / getuser()[0] / getuser() / 'mhws' / 'extreme_events_binary.zarr'
chunk_size = {'time': 25, 'lat': -1, 'lon': -1}
ds = xr.open_zarr(str(file_name), chunks=chunk_size)

In [4]:
# Extract Binary Features and Modify Mask

extreme_bin = ds.extreme_events.isel(time=slice(0, 100))
mask = ds.mask.where((ds.lat<85) & (ds.lat>-90), other=False)

In [5]:
# Tracking Parameters

drop_area_quartile = 0.5
filling_radius = 8
allow_merging = True

In [6]:
# Spot the Blobs

tracker = blob.Spotter(extreme_bin, mask, R_fill=filling_radius, area_filter_quartile=drop_area_quartile, allow_merging=allow_merging)
#blobs = tracker.run()

#blobs

In [7]:
data_bin_filled = tracker.fill_holes()

In [8]:
data_bin_filtered, area_threshold, blob_areas, N_blobs_unfiltered = tracker.filter_small_blobs(data_bin_filled)

In [9]:
data_bin = data_bin_filtered

In [10]:
blob_id_field, _ = tracker.identify_blobs(data_bin, time_connectivity=False)

In [11]:
import numpy as np
import matplotlib.pyplot as plt

In [12]:
# Calculate Properties of each Blob
blob_props = tracker.calculate_blob_properties(blob_id_field, properties=['area', 'centroid'])


In [13]:

# Compile List of Overlapping Blob ID Pairs Across Time
overlap_blobs_list = tracker.find_overlapping_blobs(blob_id_field)  # List of overlapping blob pairs


In [14]:
split_merged_blob_id_field_unique, merged_blobs_props, split_merged_blobs_list, merged_blobs_ledger = tracker.split_and_merge_blobs(blob_id_field, blob_props, overlap_blobs_list)


/home/b/b382615/opt/spot_the_blOb/spot_the_blOb/spot_the_blOb.py:630: FutureWarning: ``output_sizes`` should be given in the ``dask_gufunc_kwargs`` parameter. It will be removed as direct parameter in a future version.
  unique_ids_by_time = xr.apply_ufunc(
/home/b/b382615/opt/anaconda3/lib/python3.10/site-packages/distributed/client.py:3361: UserWarning: Sending large graph of size 99.02 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(
/home/b/b382615/opt/anaconda3/lib/python3.10/site-packages/distributed/client.py:3361: UserWarning: Sending large graph of size 99.02 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https

In [15]:
# Cluster Blobs List to Determine Globally Unique IDs & Update Blob ID Field
split_merged_blobs_ds = tracker.cluster_rename_blobs_and_props(split_merged_blob_id_field_unique, merged_blobs_props, split_merged_blobs_list)

/home/b/b382615/opt/anaconda3/lib/python3.10/site-packages/distributed/client.py:3361: UserWarning: Sending large graph of size 396.06 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(
/home/b/b382615/opt/anaconda3/lib/python3.10/site-packages/distributed/client.py:3361: UserWarning: Sending large graph of size 396.32 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(


In [16]:
# Add Merge Ledger to split_merged_blobs_ds
split_merged_blobs_ds.attrs['merge_ledger'] = merged_blobs_ledger

# Count Number of Blobs (This may have increased due to splitting)
N_blobs = split_merged_blobs_ds.ID_field.max().compute().data

/home/b/b382615/opt/anaconda3/lib/python3.10/site-packages/distributed/client.py:3361: UserWarning: Sending large graph of size 396.07 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(


In [18]:
split_merged_blobs_ds

<xarray.Dataset> Size: 416MB
Dimensions:     (lat: 721, lon: 1440, time: 100, ID: 91, component: 2)
Coordinates:
  * lat         (lat) float64 6kB -90.0 -89.75 -89.5 -89.25 ... 89.5 89.75 90.0
  * lon         (lon) float64 12kB 0.0 0.25 0.5 0.75 ... 359.0 359.2 359.5 359.8
  * time        (time) datetime64[ns] 800B 2002-01-01T23:59:00 ... 2002-04-10...
  * ID          (ID) int32 364B 1 2 3 4 5 6 7 8 9 ... 83 84 85 86 87 88 89 90 91
Dimensions without coordinates: component
Data variables:
    ID_field    (time, lat, lon) int32 415MB dask.array<chunksize=(25, 721, 1440), meta=np.ndarray>
    global_ID   (ID, time) float64 73kB 1.0 11.0 21.0 30.0 ... 0.0 0.0 0.0 0.0
    area        (ID, time) float64 73kB 1.973e+04 1.943e+04 ... nan nan
    centroid    (component, ID, time) float64 146kB 163.1 163.1 ... nan nan
    presence    (ID, time) bool 9kB True True True True ... False False False
    time_start  (ID) datetime64[ns] 728B 2002-01-01T23:59:00 ... 2002-01-01T2...
    time_end    (ID) datetime64[ns] 728B 2002-04-10T23:59:00 ... 2002-04-10T2...
Attributes:
    merge_ledger:  [array([12, 13], dtype=int32), array([107, 109], dtype=int...

In [23]:
split_merged_blobs_ds.merge_ledger

[array([12, 13], dtype=int32),
 array([107, 109], dtype=int32),
 array([118, 120, 980], dtype=int32),
 array([130, 981, 982], dtype=int32),
 array([140, 983], dtype=int32),
 array([152, 985], dtype=int32),
 array([162, 986], dtype=int32),
 array([172, 987], dtype=int32),
 array([189, 184, 988], dtype=int32),
 array([199, 197, 990], dtype=int32),
 array([210, 991, 992], dtype=int32),
 array([218, 993, 994], dtype=int32),
 array([226, 230, 228, 996], dtype=int32),
 array([235, 997], dtype=int32),
 array([ 241, 1000], dtype=int32),
 array([253, 254], dtype=int32),
 array([ 266, 1002], dtype=int32),
 array([ 275,  276, 1003], dtype=int32),
 array([ 288, 1004, 1005], dtype=int32),
 array([ 301, 1006, 1007], dtype=int32),
 array([ 312, 1009], dtype=int32),
 array([ 323, 1010], dtype=int32),
 array([ 332, 1011], dtype=int32),
 array([ 343, 1012], dtype=int32),
 array([278, 280], dtype=int32),
 array([310, 311], dtype=int32),
 array([ 320,  322, 1015], dtype=int32),
 array([ 330, 1016, 1017], 

In [ ]:
blobs.attrs

In [ ]:
# Save Tracked Blobs

file_name = Path('/scratch') / getuser()[0] / getuser() / 'mhws' / 'MHWs_tracked.nc'
blobs.to_netcdf(file_name, mode='w')